package com.akinsete.ourgrocerylist.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "GROCERY".
 */
@Entity
public class Grocery {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String last_name;
    private String first_name;

//    private int quantity;
//    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Grocery(String string, Integer integer, String cursorString) {
    }

    public Grocery() {
        this.id = id;
    }

    @Generated
    public Grocery(Long id, String name, String last_name, String first_name) {
        this.id = id;
        this.last_name = last_name;
        this.first_name = first_name;

    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return last_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.last_name = name;
    }

    public Long getid() {
        return id;
    }

    public void setFirst_name(String first_name) {
        this.first_name=first_name;

    }

    public String getFirst_name() {
        return first_name;
    }

//    public void setStatus(String status) {
//        this.status = status;
//    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END


    @Override
    public String toString() {
        return id + " " +last_name + " " + first_name ;
    }

    public void setFirstName(String s) {
    }

    public void setEmail(String s) {
    }

    public void setTelephone(String s) {
    }
}
